apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonyliv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonyliv
  template:
    metadata:
      labels:
        app: sonyliv
    spec:
      containers:
      - name: sonyliv
        image: vamsichamarthi/sonyliv:latest
        ports:
        - containerPort: 8080
